### PR TITLE
Adds profile section with ability to have a custom name. 

### PR DESCRIPTION
**Pull request by charlesmwray**

### CODE REVIEW

**Comment by ezywebs** [comment]
I got an error after accessing profile, maybe it's my environmental issue  ¯\\_(ツ)_/¯

**Comment by charlesmwray** [comment]
@ezywebs  what error did you get. I just tried again and it worked. Maybe run `npm install `as the dependencies were updated.

**Comment by ezywebs** [comment]
@charlesmwray adding screenshot per our conversation
image

**Comment by charlesmwray** [comment]
@ezywebs  I've updated with a fix.

**Review by ezywebs — APPROVED** [review]

**Pull request merged**
